import type { CityOption, LineUpArtist, LineUpShow } from '../types';

export const LINEUP_CITIES: CityOption[] = [
  {
    id: 'sao-luis',
    name: 'São Luís',
    state: 'MA',
    coordinate: { latitude: -2.5307, longitude: -44.3068 },
  },
  {
    id: 'sao-jose-ribamar',
    name: 'São José de Ribamar',
    state: 'MA',
    coordinate: { latitude: -2.5617, longitude: -44.0542 },
  },
  {
    id: 'paco-lumiar',
    name: 'Paco do Lumiar',
    state: 'MA',
    coordinate: { latitude: -2.5312, longitude: -44.1019 },
  },
];

export const LINEUP_GENRES = [
  'Todos',
  'Sertanejo',
  'Pagode',
  'Forró',
  'Rock',
  'Eletrônica',
  'MPB',
  'Trap',
] as const;

export const LINEUP_ARTISTS: LineUpArtist[] = [
  {
    id: 'jorge-mateus',
    name: 'Jorge & Mateus',
    shortName: 'Jorge M.',
    genre: 'Sertanejo',
    genres: ['Sertanejo'],
    image: 'amber',
    featured: true,
    followers: 4200000,
    origin: 'Goiás',
    biography:
      'Dupla sertaneja com repertório romântico, grandes festivais e shows de arena. No Budd, aparece como dado de desenvolvimento para validar descoberta e compra de ingressos.',
    website: 'https://www.jorgeemateus.com.br',
  },
  {
    id: 'cecilia-leite',
    name: 'Cecília Leite',
    shortName: 'Cecília',
    genre: 'MPB',
    genres: ['MPB', 'Pagode'],
    image: 'plum',
    featured: true,
    followers: 27000,
    origin: 'São Luís, MA',
    biography:
      'Cantora maranhense com show autoral, releituras de MPB e participações de artistas locais. A agenda destaca palcos intimistas e eventos de rua.',
  },
  {
    id: 'aguila',
    name: 'Águila',
    shortName: 'Águila',
    genre: 'Forró',
    genres: ['Forró'],
    image: 'green',
    followers: 40000,
    origin: 'Maranhão',
    biography:
      'Projeto de forro moderno com sanfona, percussão e repertório voltado para pistas cheias. A apresentação costuma misturar clássicos e músicas autorais.',
  },
  {
    id: 'dj-kaos',
    name: 'DJ Kaos',
    shortName: 'DJ Kaos',
    genre: 'Eletrônica',
    genres: ['Eletrônica', 'Trap'],
    image: 'violet',
    featured: true,
    followers: 52000,
    origin: 'São Luís, MA',
    biography:
      'DJ e produtor voltado para bass music, trap e noites open air. Os sets combinam faixas autorais, remixes e convidados da cena local.',
  },
  {
    id: 'banda-cazumba',
    name: 'Banda Cazumba',
    shortName: 'Cazumba',
    genre: 'Rock',
    genres: ['Rock'],
    image: 'rust',
    followers: 18000,
    origin: 'São Luís, MA',
    biography:
      'Banda de rock alternativo com referências regionais e guitarras pesadas. A agenda atual prioriza festivais independentes.',
  },
  {
    id: 'grupo-raiz',
    name: 'Grupo Raiz',
    shortName: 'Raiz',
    genre: 'Pagode',
    genres: ['Pagode', 'MPB'],
    image: 'forest',
    followers: 33000,
    origin: 'Centro Histórico, São Luís',
    biography:
      'Grupo de samba e pagode com rodas ao vivo, convidados e repertório popular. Ideal para descobrir shows próximos e eventos gratuitos.',
  },
];

export const LINEUP_SHOWS: LineUpShow[] = [
  {
    id: 'jorge-mateus-arena-budd',
    artistId: 'jorge-mateus',
    eventId: 'noite-do-sertanejo',
    title: 'Noite do Sertanejo',
    description:
      'Show de arena com repertório sertanejo, abertura de DJ convidado e setores pista, area VIP e camarote.',
    date: '16 de agosto',
    startsAt: nextLocalIso(20, 22, 0),
    endsAt: nextLocalIso(20, 2, 0, 1),
    doorsOpenAt: '20:00',
    venue: {
      id: 'arena-budd',
      name: 'Arena Budd',
      address: 'Av. dos Holandeses, 1000',
      neighborhood: 'Calhau',
      city: 'São Luís',
      state: 'MA',
      coordinate: { latitude: -2.4962, longitude: -44.2882 },
    },
    minimumPriceInCents: 8000,
    ticketStatus: 'available',
    ticketOptions: [
      { id: 'pista', label: 'Pista', type: 'pista', priceInCents: 8000, serviceFeeInCents: 800, available: 90, maxPerUser: 4 },
      { id: 'vip', label: 'Area VIP', type: 'vip', priceInCents: 16000, serviceFeeInCents: 1600, available: 18, maxPerUser: 2 },
    ],
    genres: ['Sertanejo'],
    ageRating: '16 anos',
    parkingInfo: 'Estacionamento pago no local.',
    accessibilityInfo: 'Entrada acessivel e area reservada proxima ao palco.',
    entryRules: ['Documento oficial obrigatorio.', 'Meia-entrada conforme legislacao.'],
    allowedItems: ['Documento', 'Celular', 'Capa de chuva pequena'],
    forbiddenItems: ['Garrafas', 'Objetos cortantes', 'Caixas termicas'],
    attractions: ['Jorge & Mateus', 'DJ residente'],
    eventType: 'Show',
  },
  {
    id: 'cecilia-centro',
    artistId: 'cecilia-leite',
    eventId: 'noite-samba-de-raiz',
    title: 'Noite de Samba de Raiz',
    description:
      'Roda aberta com Cecília Leite, Grupo Raiz e convidados no Centro Histórico.',
    date: 'Este domingo',
    startsAt: nextLocalIso(6, 20, 0),
    endsAt: nextLocalIso(7, 1, 0),
    doorsOpenAt: '19:00',
    venue: {
      id: 'praca-nauro',
      name: 'Praça Nauro Machado',
      address: 'Rua da Estrela, s/n',
      neighborhood: 'Centro',
      city: 'São Luís',
      state: 'MA',
      coordinate: { latitude: -2.5288, longitude: -44.3068 },
    },
    minimumPriceInCents: 0,
    ticketStatus: 'sold_out',
    ticketOptions: [],
    genres: ['MPB', 'Pagode'],
    ageRating: 'Livre',
    parkingInfo: 'Estacionamento publico nas ruas proximas.',
    accessibilityInfo: 'Praça plana, com acesso por rampas laterais.',
    attractions: ['Cecília Leite', 'Grupo Raiz'],
    eventType: 'Festival',
  },
  {
    id: 'aguila-forro-pixzinho',
    artistId: 'aguila',
    eventId: 'samba-de-raiz-ao-vivo',
    title: 'Forró de Quinta',
    description:
      'Noite de forro pe de serra com pista reduzida e entrada controlada.',
    date: 'Proxima quinta',
    startsAt: nextLocalIso(4, 21, 0),
    endsAt: nextLocalIso(5, 1, 30),
    doorsOpenAt: '20:00',
    venue: {
      id: 'pixzinho-dos-crias',
      name: 'Pixzinho Dos Crias',
      address: 'Rua Lina Figueiredo',
      neighborhood: 'Jardins de Allah',
      city: 'São Luís',
      state: 'MA',
      coordinate: { latitude: -2.5487, longitude: -44.249 },
    },
    minimumPriceInCents: 3500,
    ticketStatus: 'last_tickets',
    ticketOptions: [
      { id: 'inteira', label: 'Inteira', type: 'inteira', priceInCents: 3500, serviceFeeInCents: 350, available: 8, maxPerUser: 4 },
      { id: 'meia', label: 'Meia-entrada', type: 'meia', priceInCents: 1800, serviceFeeInCents: 180, available: 4, maxPerUser: 2 },
    ],
    genres: ['Forró'],
    ageRating: '18 anos',
    parkingInfo: 'Vagas limitadas na rua.',
    accessibilityInfo: 'Entrada terrea; banheiro adaptado indisponível.',
    attractions: ['Águila', 'Trio convidado'],
    eventType: 'Bar',
  },
  {
    id: 'dj-kaos-kommander',
    artistId: 'dj-kaos',
    eventId: 'kommander-of-kaos-iv',
    title: 'Festival Kommander of Kaos IV',
    description:
      'Festival underground com bandas autorais, DJs, food trucks e encerramento de DJ Kaos.',
    date: 'Hoje',
    startsAt: nextLocalIso(0, 15, 0),
    endsAt: nextLocalIso(0, 23, 50),
    doorsOpenAt: '15:00',
    venue: {
      id: 'anil-open-air',
      name: 'Open Air Anil',
      address: 'Av. Santos Dumont',
      neighborhood: 'Anil',
      city: 'São Luís',
      state: 'MA',
      coordinate: { latitude: -2.5423, longitude: -44.2601 },
    },
    minimumPriceInCents: 5000,
    ticketStatus: 'available',
    ticketOptions: [
      { id: 'pista', label: 'Pista', type: 'pista', priceInCents: 5000, serviceFeeInCents: 500, available: 12, maxPerUser: 4 },
      { id: 'vip', label: 'VIP', type: 'vip', priceInCents: 12000, serviceFeeInCents: 1200, available: 3, maxPerUser: 2 },
    ],
    genres: ['Eletrônica', 'Trap', 'Rock'],
    ageRating: '18 anos',
    parkingInfo: 'Estacionamento privado ao lado do evento.',
    accessibilityInfo: 'Area principal plana e equipe de apoio na entrada.',
    forbiddenItems: ['Bebidas externas', 'Objetos perfurantes'],
    attractions: ['DJ Kaos', 'Bandas autorais', 'Food trucks'],
    eventType: 'Festival',
  },
  {
    id: 'banda-cazumba-sunset',
    artistId: 'banda-cazumba',
    eventId: 'sunset-underground',
    title: 'Sunset Underground',
    description:
      'Show de rock alternativo ao por do sol com line-up independente.',
    date: 'Sabado',
    startsAt: nextLocalIso(5, 18, 0),
    endsAt: nextLocalIso(5, 23, 0),
    doorsOpenAt: '17:00',
    venue: {
      id: 'espigao-costeiro',
      name: 'Espigão Costeiro',
      address: 'Av. Litoranea',
      neighborhood: 'Ponta d Areia',
      city: 'São Luís',
      state: 'MA',
      coordinate: { latitude: -2.4919, longitude: -44.3053 },
    },
    minimumPriceInCents: 3000,
    ticketStatus: 'cancelled',
    ticketOptions: [],
    genres: ['Rock'],
    ageRating: '16 anos',
    parkingInfo: 'Vagas publicas sujeitas a disponibilidade.',
    accessibilityInfo: 'Evento em area externa com piso irregular.',
    attractions: ['Banda Cazumba', 'DJ convidado'],
    eventType: 'Show',
  },
  {
    id: 'grupo-raiz-karaoke',
    artistId: 'grupo-raiz',
    eventId: 'karaoke-fernanda-silva',
    title: 'Karaokê e Pagode',
    description:
      'Noite gratuita com karaoke, roda de pagode e premiacao para apresentacoes.',
    date: 'Em 2 dias',
    startsAt: nextLocalIso(2, 21, 0),
    endsAt: nextLocalIso(3, 1, 0),
    doorsOpenAt: '20:30',
    venue: {
      id: 'cosme-brito',
      name: 'Cosme Brito',
      address: 'Rua Alto da Paz, 47 B',
      neighborhood: 'Aurora',
      city: 'São Luís',
      state: 'MA',
      coordinate: { latitude: -2.5561, longitude: -44.2432 },
    },
    minimumPriceInCents: 0,
    ticketStatus: 'available',
    ticketOptions: [],
    genres: ['Pagode', 'MPB'],
    ageRating: 'Livre',
    parkingInfo: 'Vagas na rua.',
    accessibilityInfo: 'Entrada sem degrau.',
    attractions: ['Grupo Raiz', 'Fernanda Silva'],
    eventType: 'Bar',
  },
];

function nextLocalIso(dayOffset: number, hour: number, minute: number, extraDay = 0): string {
  const now = new Date();
  return new Date(
    now.getFullYear(),
    now.getMonth(),
    now.getDate() + dayOffset + extraDay,
    hour,
    minute,
  ).toISOString();
}
